// This file is generated by GoAdmin CLI adm.
package tables

import (
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "users" => http://localhost:9033/admin/info/users
// "mall_goods" => http://localhost:9033/admin/info/mall_goods
// "mall_goods_sku" => http://localhost:9033/admin/info/mall_goods_sku
//
// example end
var Generators = map[string]table.Generator{

	"mall_goods":     GetMallGoodsTable,
	"mall_goods_sku": GetMallGoodsSkuTable,

	// generators end
}
